### ISSUE TITLE
create2

### ISSUE THREAD

**Issue by aliabdolazimi** [OpenZeppelin/openzeppelin-upgrades#390] opened 2021-07-15 05:39 UTC
Upgrades Plugins do not support create2 and  cant use create2 with upgrade plugins

**Comment by Amxx** [comment] 2021-07-15 11:47
Hello @aliabdolazimi 

Note that the upgrade plugin is designed to work with any blockchain. At the same time, EOA cannot create contract using create2, only factory contract can make use of this opcode.

AFAIK, there are two ways of deploying contract in a counterfactual manner:

- create a custom transaction with a specific signature that doesn't come from an EOA (only zeros ?) and fund the corresponding wallet, for which the private key is unknown
- use a generic create2 factory like the one available at [0xfAC000a12dA42B871c0AaD5F25391aAe62958Db1](https://etherscan.io/address/0xfAC000a12dA42B871c0AaD5F25391aAe62958Db1)

Neither of these is natively supported by the plugin. We may want to add custom deployment scripts/functions in the future. For now, you can always deploy the implementation yourself, and use the corresponding address to create/upgrade proxies.

**Comment by frangio** [comment] 2021-07-15 13:45
Duplicate of #358

**Closed by frangio** 2021-07-15 13:45 UTC
