### ISSUE TITLE
Support specifying address to deploy from

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-upgrades#181] opened 2020-09-21 02:50 UTC
Support specifying address to deploy from, e.g. `deployProxy(..., {deployer, from: accounts[1]})`

Truffle uses the default account (accounts[0]) for `deployProxy` in tests and migrations and there doesn't appear to be a way to specify a from option (unless this is part of the Deployer object).

Raised in the community forum: https://forum.openzeppelin.com/t/setting-the-from-address-for-a-proxy-deployment-in-a-test/3821

**Comment by frangio** [comment] 2020-10-01 22:49
Duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85.

**Closed by frangio** 2020-10-01 22:49 UTC
