### ISSUE TITLE
@openzeppelin/hardhat-upgrades changes "deployContract()" ?

### ISSUE THREAD

**Issue by Taewa** [OpenZeppelin/openzeppelin-upgrades#848] opened 2023-07-23 14:20 UTC
I am facing an issue with `@openzeppelin/hardhat-upgrades` during a deployment of contracts on my local.

Here is a simplified example.

```typescript
// hardhat.config.ts
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import '@openzeppelin/hardhat-upgrades'; // <- note: importing the hardhat-upgrades

const config: HardhatUserConfig = {
  solidity: "0.8.19",
};

export default config;
```
Then deploying script

```typescript
import { ethers } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  const myContract = await ethers.deployContract("MyContract", [deployer.address]);

  await myContract.waitForDeployment();  // <- Got an error: TypeError: myContract.waitForDeployment is not a function
...

```

As you can see that `waitForDeployment` is not a function.
However, when I remove `import '@openzeppelin/hardhat-upgrades';` and re-deploy, it works.
That being said `deployContract()` is modified by something and I assume it might be `hardhat-upgrades` but not sure what actually causes that issue and that's why I am asking here.

FYI: I need 1 contract proxy and the other one for just normal contract (without proxy) and that's why I am trying to use `hardhat-upgrades`.

Thanks in advance!

**Comment by ericglau** [comment] 2023-07-24 14:57
Hi @Taewa, I tried this and couldn't reproduce your issue.  Can you share what your package.json's dependencies look like and/or the output of `npm list`?

**Comment by ericglau** [comment] 2023-08-18 15:42
Closing as this could not be reproduced.  If this still occurs, feel free to reopen with the above information.

**Closed by ericglau** 2023-08-18 15:42 UTC
