### ISSUE TITLE
deployProxy function doesn't work for Optimism (OVM) network

### ISSUE THREAD

**Issue by guanzhenxing** [OpenZeppelin/openzeppelin-upgrades#311] opened 2021-03-12 02:23 UTC
I want to deploy a proxy contract at optimism network,but it not work.

My code like:
```
 let WePiggyPriceOracleV1 = await l2ethers.getContractFactory("WePiggyPriceOracleV1", {
        signer: (await ethers.getSigners())[0]
    });
    let wepiggy_price_oracle_v1 = await upgrades.deployProxy(WePiggyPriceOracleV1);
    await wepiggy_price_oracle_v1.deployed();
```
and the result is:
```
  ganache Optional dependencies installed; exporting ganache-core with native optional dependencies. +0ms
  ganache Optional dependencies installed; exporting ganache-core with native optional dependencies. +0ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Creating provider for network optimism +76ms
  @openzeppelin:upgrades:core fetching deployment of implementation 2f3b6eebb3cb5fdeebbe55176512a04c88e435fb352f67e540dcfdacef496e4c +0ms
  @openzeppelin:upgrades:core deployment of implementation 2f3b6eebb3cb5fdeebbe55176512a04c88e435fb352f67e540dcfdacef496e4c not found +1ms
  @openzeppelin:upgrades:core initiated deployment 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +12s
  @openzeppelin:upgrades:core verifying deployment tx mined 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +6ms
  @openzeppelin:upgrades:core succeeded verifying deployment tx mined 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +1s
  @openzeppelin:upgrades:core fetching deployment of proxy admin +2s
  @openzeppelin:upgrades:core deployment of proxy admin not found +1ms
  @openzeppelin:upgrades:core initiated deployment 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +10s
  @openzeppelin:upgrades:core verifying deployment tx mined 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +1ms
  @openzeppelin:upgrades:core succeeded verifying deployment tx mined 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +1s
{ Error: Invalid deployment with address 0xeB4cbbCE5B52ca1b167898dac418da2C68ca9c01 and txHash 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79
    at Object.waitAndValidateDeployment (/Users/dev/piggy/piggy-contract/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:77:4)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  deployment:
   { address: '0xeB4cbbCE5B52ca1b167898dac418da2C68ca9c01',
     txHash:
      '0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79' } }
```

And I found this code at @openzeppelin/hardhat-upgrades/src/proxy-factory.ts
```
import AdminUpgradeabilityProxy from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/AdminUpgradeabilityProxy.sol/AdminUpgradeabilityProxy.json';
import ProxyAdmin from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/ProxyAdmin.sol/ProxyAdmin.json';
```
but the optimism use AdminUpgradeabilityProxy-ovm.json and ProxyAdmin-ovm.json . Is it a bug ? 

Thanks!

**Comment by georgeroman** [comment] 2021-03-14 14:17
This seems very similar to the issue in https://forum.openzeppelin.com/t/openzeppelin-upgrades-support-for-optimism/5511.

**Comment by abcoathup** [comment] 2021-03-15 01:13
Duplicate of #309

**Closed by abcoathup** 2021-03-15 01:13 UTC

**Comment by abcoathup** [comment] 2021-03-15 01:21
I have closed this issue as a duplicate.
