### ISSUE TITLE
Deploy proxy does not support custom gas price

### ISSUE THREAD

**Issue by ne2030** [OpenZeppelin/openzeppelin-upgrades#556] opened 2022-04-11 04:49 UTC
`deployProxy` or `deployBeaconProxy` seems to not support custom gas price as option including legacy gasPrice option and EIP 1559 options.
I checked internal code implementation and find out that custom options are not delivered to ethers' deploy function.
I think simply deliver gas options to deploy function would make things work! 

```javascript const BeaconProxyFactory = await getBeaconProxyFactory(hre, attachTo.signer);
    const proxyDeployment: Required<ProxyDeployment & DeployTransaction> = Object.assign(
      { kind: opts.kind },
      await deploy(BeaconProxyFactory, beaconAddress, data),
    );
```

**Comment by frangio** [comment] 2022-04-11 13:59
Duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85

**Closed by frangio** 2022-04-11 13:59 UTC
