### ISSUE TITLE
Proxy admin is not the one registered in the network manifest

### ISSUE THREAD

**Issue by arijoon** [OpenZeppelin/openzeppelin-upgrades#725] opened 2023-01-25 15:15 UTC
This error is thrown if the admin in manifest does not match your proxy's admin. Please add a method of skipping this check as some usecases may want multiple admins per network. For example in our case, we need multiple environments each with their own keys (i.e. need different admin proxy), but on same network. The only solution I've found so far is to manually modify the manifest file before deployment to set the admin.
Ideally the admin proxy can be further keyed by a provided env option or the user address running the script

full error:
```
Error: Proxy admin is not the one registered in the network manifest
    at getUpgrader (/path/to/project/.yarn/__virtual__/@openzeppelin-hardhat-upgrades-virtual-c68f211f86/0/cache/@openzeppelin-hardhat-upgrades-npm-1.21.0-f2789fd1f0-dada5df033.zip/node_modules/@openzeppelin/hardhat-upgrades/src/upgrade-proxy.ts:59:15)
```

**Comment by frangio** [comment] 2023-01-26 22:33
This may be a duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/136.

I do think that we should implement this.

**Comment by ericglau** [comment] 2023-08-18 15:32
Fixed by https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/859

**Closed by ericglau** 2023-08-18 15:32 UTC
