### ISSUE TITLE
Error: Artifact does not contain AST

### ISSUE THREAD

**Issue by allemanfredi** [OpenZeppelin/openzeppelin-upgrades#176] opened 2020-09-18 13:00 UTC
Hey guys! Just tried to use the plugin but when i try to use __`deployProxy`__ within tests i receive the following error: `Error: Artifact does not contain AST`.

Solidity version: 0.7.1
Truffle version: 5.1.35
Node: 12.16.2
@openzeppelin/truffle-upgrades: 1.0.2

**Comment by frangio** [comment] 2020-09-18 17:57
Hi @allemanfredi, I wasn't able to reproduce this issue. The setup below worked for me:

```js
// truffle.config.js
module.exports = {
  compilers: {
    solc: {
      version: "0.7.1",
    }
  }
}
```

```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.8.0;

contract Box { }
```

```js
// test/Box.test.js
const Box = artifacts.require('Box');
const { deployProxy } = require('@openzeppelin/truffle-upgrades');

contract('Box', function () {
  it('works', async function () {
    await deployProxy(Box);
  });
});
```

Can you share more details about your setup and files and the exact steps you're following?

**Comment by allemanfredi** [comment] 2020-09-19 08:25
Thanks for your response! i saw that you don't use  __Initializable__ contract and __initializer__ modifier. Could this be the problem?

This is my setup:

```solidity
Contract Hello is Initializable {

    function initialize(address _a) public initializer { .....
```

```js
solc: {
  version: "0.7.1",
  settings: { 
  optimizer: {
      enabled: true,
      runs: 200
   },
}
```
```js
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades')
const Hello = artifacts.require('Hello')

contract('Hello', ([account, ...accounts]) => {
    beforeEach(async () => {
        await deployProxy(Hello, [account])
    })
})
```

**Comment by julianmrodri** [comment] 2020-09-19 16:49
Hi @allemanfredi I was able to run the scenario you mention successfully with the same environment.

One thing I noticed is that `Initializable` has to be imported from the `@openzeppelin/contracts` package in order to support version `0.7.1` (as the one included in `@openzeppelin/truffle-upgrades@1.02` does not support it. 

Are you sure you are importing the correct version? Also can you check if by just running `truffle compile` you get the artifacts (`.json`) in the `build/contracts` folder correctly and if they include an `ast` item?  It would be very helpful to have the complete code so we can replicate exactly what you are running.

This is how the generated artifact with the `AST` should look like:

```js
// build/contracts/Hello.json
"{
  contractName": "Hello",
    "abi": [{...}],
    "metadata": "{\"compiler\":{\"version\":\"0.7.1+commit.f4a555be\"},\"language\":\"Solidity\",\"... }"output\":{\"abi\":[{\"inputs\":
    "bytecode": "0x60806040523480156100105 .... ",
    "deployedBytecode":"0x60806040523480156100105..... ",
    .....
    "ast": { ... },
    ....
}
```

This is the example I ran:
 - @openzeppelin/truffle-upgrades:  1.0.2
 - @openzeppelin/contracts:  3.2.1-solc-0.7
 - Truffle:  5.1.35
-  Node:  12.16.1

```js
// truffle-config.js
compilers: {
    solc: {
      version: "0.7.1",
      settings: { 
      optimizer: {
          enabled: true,
          runs: 200
       },
    }
  }
```

```solidity
// Hello.sol
pragma solidity 0.7.1;

import "@openzeppelin/contracts/proxy/Initializable.sol";

contract Hello is Initializable { 

    address public addr;

    function initialize(address _a) public initializer {
       addr = _a;
    }
}
```

```js
// test_script.js
const { deployProxy } = require('@openzeppelin/truffle-upgrades')
const Hello = artifacts.require('Hello')

contract('Hello', ([account, ...accounts]) => {
    let proxy;
    beforeEach(async () => {
        proxy = await deployProxy(Hello, [account])
    })

    it("should setup address", () => {
        return proxy.addr()
       .then((addr) => {
        assert.equal(
          addr,
          account,
          "Address not setup"
        );
      });
    }) 
})

```

**Comment by allemanfredi** [comment] 2020-09-21 05:56
Yes i'm using the right version of `Initializable`. I try again and i'll let you know! thanks for your help!

**Comment by frangio** [comment] 2020-10-01 22:24
@allemanfredi Were you able to solve this issue?

**Comment by allemanfredi** [comment] 2020-10-02 19:52
@frangio Unfortunately i didn't try anymore.

**Comment by frangio** [comment] 2020-11-24 20:22
Closing since we couldn't reproduce the issue.

**Closed by frangio** 2020-11-24 20:22 UTC
