### ISSUE TITLE
Can't install from npm

### ISSUE THREAD

**Issue by kvakes** [OpenZeppelin/openzeppelin-upgrades#521] opened 2022-02-23 08:55 UTC
I ran `npm i --save-dev @openzeppelin/hardhat-upgrades` today. Here's the output:

```
npm install --save-dev @openzeppelin/hardhat-upgrades
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @nomiclabs/hardhat-ethers@0.3.0-beta.13
npm ERR! node_modules/@nomiclabs/hardhat-ethers
npm ERR!   dev @nomiclabs/hardhat-ethers@"npm:hardhat-deploy-ethers@^0.3.0-beta.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nomiclabs/hardhat-ethers@"^2.0.0" from @openzeppelin/hardhat-upgrades@1.14.0
npm ERR! node_modules/@openzeppelin/hardhat-upgrades
npm ERR!   dev @openzeppelin/hardhat-upgrades@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

`yarn add "@openzeppelin/hardhat-upgrades" -D` worked just fine

**Comment by frangio** [comment] 2022-02-23 19:22
Thanks for reporting @kvakes. This really looks more like an npm issue so I'll go ahead and close it. Let us know if it happens consistently with this package.

**Closed by frangio** 2022-02-23 19:22 UTC

**Comment by 0x-Avant-Garde** [comment] 2023-12-08 04:57
I can confirm that this issue is still happening.
```
npm install --save-dev @openzeppelin/hardhat-upgrades
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @nomicfoundation/hardhat-verify@2.0.2
npm ERR! node_modules/@nomicfoundation/hardhat-verify
npm ERR!   peer @nomicfoundation/hardhat-verify@"^2.0.0" from @nomicfoundation/hardhat-toolbox@4.0.0
npm ERR!   node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!     dev @nomicfoundation/hardhat-toolbox@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @openzeppelin/hardhat-upgrades@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @nomicfoundation/hardhat-verify@1.1.1
npm ERR! node_modules/@nomicfoundation/hardhat-verify
npm ERR!   peerOptional @nomicfoundation/hardhat-verify@"^1.1.0" from @openzeppelin/hardhat-upgrades@2.5.0
npm ERR!   node_modules/@openzeppelin/hardhat-upgrades
npm ERR!     dev @openzeppelin/hardhat-upgrades@"*" from the root project
```

**Comment by daithi-coombes** [comment] 2023-12-14 16:25
same issue here:
```
$ node -v
v18.16.0
$ npm -v
9.7.1
```
Hardhat version is latest at `^2.19.2`.

Stdout:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: feipay-eip-4337@0.0.1-beta
npm ERR! Found: ethers@5.7.2
npm ERR! node_modules/ethers
npm ERR!   ethers@"^5.7.1" from @nomicfoundation/ethereumjs-block@5.0.2
npm ERR!   node_modules/@nomicfoundation/ethereumjs-block
npm ERR!     @nomicfoundation/ethereumjs-block@"5.0.2" from @nomicfoundation/ethereumjs-blockchain@7.0.2
npm ERR!     node_modules/@nomicfoundation/ethereumjs-blockchain
npm ERR!       @nomicfoundation/ethereumjs-blockchain@"7.0.2" from @nomicfoundation/ethereumjs-vm@7.0.2
npm ERR!       node_modules/@nomicfoundation/ethereumjs-vm
npm ERR!         @nomicfoundation/ethereumjs-vm@"7.0.2" from hardhat@2.19.2
npm ERR!         node_modules/hardhat
npm ERR!       1 more (hardhat)
npm ERR!     @nomicfoundation/ethereumjs-block@"5.0.2" from @nomicfoundation/ethereumjs-ethash@3.0.2
npm ERR!     node_modules/@nomicfoundation/ethereumjs-ethash
npm ERR!       @nomicfoundation/ethereumjs-ethash@"3.0.2" from @nomicfoundation/ethereumjs-blockchain@7.0.2
npm ERR!       node_modules/@nomicfoundation/ethereumjs-blockchain
npm ERR!         @nomicfoundation/ethereumjs-blockchain@"7.0.2" from @nomicfoundation/ethereumjs-vm@7.0.2
npm ERR!         node_modules/@nomicfoundation/ethereumjs-vm
npm ERR!         1 more (hardhat)
npm ERR!     2 more (@nomicfoundation/ethereumjs-vm, hardhat)
npm ERR!   ethers@"^5.7.1" from @nomicfoundation/ethereumjs-statemanager@2.0.2
npm ERR!   node_modules/@nomicfoundation/ethereumjs-statemanager
npm ERR!     @nomicfoundation/ethereumjs-statemanager@"2.0.2" from @nomicfoundation/ethereumjs-vm@7.0.2
npm ERR!     node_modules/@nomicfoundation/ethereumjs-vm
npm ERR!       @nomicfoundation/ethereumjs-vm@"7.0.2" from hardhat@2.19.2
npm ERR!       node_modules/hardhat
npm ERR!         peer hardhat@"^2.9.4" from @nomicfoundation/hardhat-chai-matchers@1.0.6
npm ERR!         node_modules/@nomicfoundation/hardhat-chai-matchers
npm ERR!         9 more (@nomicfoundation/hardhat-network-helpers, ...)
npm ERR!     @nomicfoundation/ethereumjs-statemanager@"2.0.2" from hardhat@2.19.2
npm ERR!     node_modules/hardhat
npm ERR!       peer hardhat@"^2.9.4" from @nomicfoundation/hardhat-chai-matchers@1.0.6
npm ERR!       node_modules/@nomicfoundation/hardhat-chai-matchers
npm ERR!         peer @nomicfoundation/hardhat-chai-matchers@"^1.0.0" from @nomicfoundation/hardhat-toolbox@2.0.2
npm ERR!         node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!       9 more (@nomicfoundation/hardhat-network-helpers, ...)
npm ERR!   6 more (@nomicfoundation/hardhat-chai-matchers, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @openzeppelin/hardhat-upgrades@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ethers@6.9.0
npm ERR! node_modules/ethers
npm ERR!   peer ethers@"^6.6.0" from @openzeppelin/hardhat-upgrades@3.0.0
npm ERR!   node_modules/@openzeppelin/hardhat-upgrades
npm ERR!     dev @openzeppelin/hardhat-upgrades@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/pip/.npm/_logs/2023-12-14T16_16_55_239Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/pip/.npm/_logs/2023-12-14T16_16_55_239Z-debug-0.log
```

**Comment by ericglau** [comment] 2023-12-14 19:52
@0x-Avant-Garde [`@openzeppelin/hardhat-upgrades@3.0.0`](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%403.0.0) uses `@nomicfoundation/hardhat-verify@^2.0.0` as a peer dependency, so will resolve your error.

@daithi-coombes `@openzeppelin/hardhat-upgrades@3.0.0` requires ethers v6.  It looks like you are on ethers v5.

**Comment by NFTYieldFarm** [comment] 2023-12-15 09:37
> @0x-Avant-Garde [`@openzeppelin/hardhat-upgrades@3.0.0`](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%403.0.0) uses `@nomicfoundation/hardhat-verify@^2.0.0` as a peer dependency, so will resolve your error.  Note that there are some breaking changes, please see the release notes.


Thanks, I figured an update to the upgrades plugin was coming soon!  In the meantime downgrading to v2.19.0 fixed the problem.

**Comment by daithi-coombes** [comment] 2023-12-16 14:45
@ericglau thanks :+1: 

Seems my issue was a old version of hardhat-toolbox (I blame a copy/paste when scaffolding my project :shushing_face: )
