### ISSUE TITLE
Forking Mainnet With Upgrades Package

### ISSUE THREAD

**Issue by jake-sanjuan** [OpenZeppelin/openzeppelin-upgrades#346] opened 2021-04-27 21:35 UTC
Hello all,

I am attempting to test a set of upgradeable contracts using the mainnet forking abilities on Hardhat.  Unfortunately, whenever I attempt to run my tests I receive this error message: 
```
Error: Invalid deployment with address 0x09635F643e140090A9A8Dcd712eD6285858ceBef and txHash 0xd9e10e22b3ac93529b4563a615cb341a2f11832eef7df79d22c8e090b1e60a9a
```
With this stack trace:
```
at Object.resumeOrDeploy (node_modules/@openzeppelin/upgrades-core/src/deployment.ts:35:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at /Users/jacobsanjuan/Desktop/Tokemak/fractal-smart-contracts/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:33:23
      at Manifest.lockedRun (node_modules/@openzeppelin/upgrades-core/src/manifest.ts:90:14)
      at fetchOrDeployGeneric (node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:25:24)
      at Proxy.deployProxy (node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:45:18)
      at Context.<anonymous> (test-unit/Manager.test.js:27:15)
```
At this line of code in my test file:
```
manager = await upgrades.deployProxy(managerFactory, [CYCLE_DURATION], { unsafeAllow: ['delegatecall'] });
```
I have done a lot of research on this issue and am aware that this issue is very similar to the one resolved in issue #282, but I am still having problems.  I am using the latest version of OpenZeppelin Hardhat Upgrades (^1.6.0) and have tried both Infura and Alchemy on both the mainnet and testnets, and am still having issues.  Please let me know what further information is needed.

**Comment by abcoathup** [comment] 2021-04-28 06:28
Hi @jake-sanjuan!   

I’m sorry that you had this issue.

Unfortunately, I wasn’t able to reproduce this issue. I tried the following:

1. `Box.sol` contract, `Box.js`, `Box.proxy.js` from: https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-hardhat/3580

## hardhat.config.js
Configure Hardhat fork 
```js
// hardhat.config.js
const { alchemyApiKey, mnemonic, etherscanApiKey } = require('./secrets.json');

require("@nomiclabs/hardhat-ethers");
require('@openzeppelin/hardhat-upgrades');

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.7.3",
  networks: {
    hardhat: {
      forking: {
        url: `https://eth-mainnet.alchemyapi.io/v2/${alchemyApiKey}`
      }
    }
  }
};
``` 
Test runs using mainnet fork
```
$ npx hardhat test --network hardhat


  Box
    ✓ retrieve returns a value previously stored

  Box (proxy)
    ✓ retrieve returns a value previously initialized


  2 passing (13s)
```

Can you try creating a simple example (such as using `Box.sol`) to illustrate the issue?

**Comment by jake-sanjuan** [comment] 2021-04-28 10:44
Hi @abcoathup 

Thanks for getting back to me quickly.  I recreated using `Box.sol`, `Box.js` and `Box.proxy.js`.  The problems seems to be in my `hardhat.config.js` file, specifically with `chainId`.  Here is where it is the config file:
```
require("dotenv").config();
require("solidity-coverage");
require("@nomiclabs/hardhat-ethers");
require("@nomiclabs/hardhat-waffle");
require("@nomiclabs/hardhat-truffle5");
require("@nomiclabs/hardhat-etherscan");
require("@openzeppelin/hardhat-upgrades");

module.exports = {
  networks: {
    hardhat: {
      chainId: 1, // This seems to be the problem
      forking: {
        url: "https://eth-mainnet.alchemyapi.io/v2/" + process.env.ALCHEMY_API_KEY,
      },
    },
    localhost: {
      url: "http://127.0.0.1:8545",
      timeout: 1000000,
    },
    coverage: {
      url: "http://localhost:8555",
    },
    mainnet: {
      url: "https://eth-mainnet.alchemyapi.io/v2/" + process.env.ALCHEMY_API_LEY,
      gasPrice: 72e9,
      accounts: {
        mnemonic: process.env.MNEMONIC || "",
      },
      timeout: 1000000,
    },
  },
  solidity: {
    version: "0.6.11",
    settings: {
      optimizer: {
        enabled: true,
        runs: 999999,
      },
    },
  },
  mocha: {
    timeout: 1000000,
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};

```
When adding the `chainId` to the config file for the Box project and running the tests twice, I get the same error:
```
Box (proxy)
       "before each" hook for "retrieve returns a value previously initialized":
     Error: Invalid deployment with address 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E and txHash 0x0c7fb14c79fa57fe32d0a4261e0aaedfa6bb7a7fd2937ce90bf9adf97c58222f
```
The tests work as expected the first time they are run.  After that, the `Box.proxy.js` test fails every time with the above error.

Config that recreates error for Box project:
```
require("@nomiclabs/hardhat-waffle");
const { alchemyApiKey } = require('./secrets.json');

require("@nomiclabs/hardhat-ethers");
require('@openzeppelin/hardhat-upgrades');

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.6.11",
  networks: {
    hardhat: {
      chainId: 1,
      forking: {
        url: `https://eth-mainnet.alchemyapi.io/v2/${alchemyApiKey}`
      }
    }
  }
};

```

**Comment by abcoathup** [comment] 2021-04-29 03:21
Hi @jake-sanjuan,

Running the tests twice reproduced the issue:

I had to modify the tests to add `  this.timeout(0);` so they didn't timeout.  Running twice gave the error:
```
$ npx hardhat test --network hardhat
Compiling 1 file with 0.7.3
Compilation finished successfully


  Box
    ✓ retrieve returns a value previously stored

  Box (proxy)
    ✓ retrieve returns a value previously initialized


  2 passing (1m)

$ npx hardhat test --network hardhat


  Box
    1) "before each" hook for "retrieve returns a value previously stored"

  Box (proxy)
    ✓ retrieve returns a value previously initialized


  1 passing (4m)
  1 failing

  1) Box
       "before each" hook for "retrieve returns a value previously stored":
     FetchError: request to https://eth-mainnet.alchemyapi.io/v2/JPV2MMxt6g3rmMY_8b8u3dMOh1gr2VV5 failed, reason: connect ETIMEDOUT 54.88.86.19:443
      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1461:11)
      at TLSSocket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:91:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.

**Comment by frangio** [comment] 2021-04-29 14:30
> The tests work as expected the first time they are run. After that, the Box.proxy.js test fails every time with the above error.

This makes sense. What's happening is that when you run the first test, it stores the deployment in your network file, and in the second run it sees that the deployment for this particular implementation contract has already been made, but the network was reset, so when it tries to reuse it it actually sees that there is no code in it, and that's when the error you're seeing gets triggered.

The reason setting the chain id causes this problem is that the usual Hardhat Network chain id gets special treatment: we know it's an ephemeral network so when we see an invalid deployment we ignore it. For mainnet, we consider this situation unexpected and bubble the error up for the user to handle it.

But I can see a couple of reasons why you'd need to set chain id to 1. On one hand, the metadata for your current implementation version may not be stored in the network file for another chan id (we can solve this with https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/175), but the proxy admin contract also won't be in the network file, and this may be an error though I think we can also fix it.

Are there other reasons why you need chain id set to 1?

**Comment by jake-sanjuan** [comment] 2021-04-30 10:17
Thank you for the explanation this makes a lot of sense.  What I am writing is part of a larger project, which has been using the chainId to check a signer against a particular id in the test cases of another contract.

**Comment by frangio** [comment] 2021-04-30 23:52
Got it. We'll change this so a deployment with a tx that can't be found in the network is always ignored, not only on Hardhat Network. May be on Monday, sorry about the delay.

**Comment by frangio** [comment] 2021-05-03 23:01
@jake-sanjuan This should be fixed on the latest release of `@openzeppelin/upgrades-core`.

In the end we fixed it by using `web3_clientVersion` to check if the node is Hardhat Network or Ganache, regardless of its chain id. But this should fix it for you.

**Closed by frangio** 2021-05-03 23:01 UTC

**Comment by jake-sanjuan** [comment] 2021-05-04 12:57
Solved, thank you for doing that, you guys rock!
