### ISSUE TITLE
passing msg.value to payable initializers

### ISSUE THREAD

**Issue by Honour-d-dev** [OpenZeppelin/openzeppelin-upgrades#953] opened 2023-12-28 11:55 UTC
the `upgrades.deployProxy()` function doesn't provide the option for passing value to the initializer along side it's arguments.
is there a possible workaround? or a way to call the initializer directly?

**Comment by ericglau** [comment] 2024-01-16 13:50
This looks like a duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/538

**Closed by ericglau** 2024-01-16 13:50 UTC
