### ISSUE TITLE
Add option for silencing warnings

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-upgrades#238] opened 2020-11-24 12:12 UTC

**Comment by frangio** [comment] 2020-11-24 17:36
Duplicate of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/226.

Note that we are considering printing a single warning rather than disabling them entirely.

**Closed by frangio** 2020-11-24 17:36 UTC

**Comment by frangio** [comment] 2020-11-26 16:04
@thegostep In case you didn't see it we've added a function to silence warnings in the latest release.

[@openzeppelin/hardhat-upgrades@1.4.0](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%401.4.0)
